# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: ocean
  theme_night: ocean
  font: minimal
  font_size: L

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer
footer:
  block: minimal
  copyright:
    notice: ''

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    theme_light: dracula
    theme_dark: dracula
    extra_languages:
      - bash
      - java
      - python
      - prolog
      - r
      - shell
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: ''
    content_dir: ''
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions
extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
